server:
  port: 9000
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 10000
zuul:
  host:
    socket-timeout-millis: 60000 #zuul的socket超时设置
    connect-timeout-millis: 60000 #zuul的connect超时设置
    forceOriginalQueryStringEncoding: true #强制采用原始请求的编码格式，即不对Get请求参数做编解码
    ignored-patterns: /*-server/** #忽略匹配这个格式的路径